### ISSUE TITLE
How to loop through records with Swoole\Coroutine\MySQL

### ISSUE THREAD

**Issue by vasily-kartashov** [swoole/swoole-src#2106]
At the moment `Statement::execute` returns a complete record set, which can be quite expensive if we're fetching 1000s of rows. Is there are way to loop "lazily"  through records, as in

```
$result = $statement->executeAndIterate([...]);
foreach ($result as $record) {
    print_r($record);
}
```

**Comment by flddr** [comment]
Hmm... On one side, there is the SQL server which should give you all requested data, on the other side there is something that requested all of this data.

So i am not really sure if the answer is simply: this should be done SQL side otherwise you got all the data (or parts) you have queried.

SQL has dozens of commands to sort, limit, filter in every direction. This is exactly the job and capability of a SQL server. And if it isn't able to do what you need, you must loop through all you get... But mostly - whenever possible - what possible should be done by SQL server. It should be optimized for your needs...

**Comment by flddr** [comment]
Btw.. if MySQL does not fit your needs, look at postgres. If you need maximum performance redis. If you need maximum capabilities maybe arrangodb (it has builtin JavaScript for all your jobs) can help you

**Comment by vasily-kartashov** [comment]
I was looking for something analogous to `mysqli`s way of doing it, something like:

```
if ($statement = $mysql->prepare($query)) {
    $statement->execute();
    while (($row = $stmt->fetch()) !== null) {
       yield $row;
    }
    $statement->close();
}
```

Note how `yield` allows as to create a `Generator`, that is economical with respect to memory consumption.

**Comment by matyhtf** [comment]
Nonsupport yet.
Now we can use `Swoole\Runtime::enableCoroutine` to  convert PDO to coroutine mode. We directly replaced the function pointer of zendvm socket stream.

```php
go(function () {
    Swoole\Runtime::enableCoroutine();
    $dbh = new PDO($dsn, $user, $password);
    if ($statement = $mysql->prepare($query)) {
        $statement->execute();
        while (($row = $stmt->fetch()) !== null) {
            //$row;
        }
        $statement->close();
    }
});
```
