### ISSUE TITLE
WebSocket Server max_request issue

### ISSUE THREAD

**Issue by yueyuzhao** [swoole/swoole-src#2140]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

```
<?php

$server = new Swoole\WebSocket\Server("0.0.0.0", 9501);

$server->set([
    'max_request' => 10,
]);

$server->on('open', function (Swoole\WebSocket\Server $server, $request) {
    echo "server: handshake success with fd{$request->fd}\n";
    $server->tick(1000, function ($id) use($server, $request) {
        print("Ping \n");
        if (!$server->exist($request->fd) || !$server->push($request->fd, "Ping", 0x9)) {
            $server->clearTimer($id);
        }
    });
});

$server->on('message', function (Swoole\WebSocket\Server $server, $frame) {
    echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
    $server->push($frame->fd, "this is server");
});

$server->on('close', function ($ser, $fd) {
    echo "client {$fd} closed\n";
});

$server->on('request', function (swoole_http_request $request, swoole_http_response $response) {
    $response->end(<<<HTML
    <h1>Swoole WebSocket Server</h1>
    <script>
var wsServer = 'ws://127.0.0.1:9501';
var websocket = new WebSocket(wsServer);
websocket.onopen = function (evt) {
    for (var i = 0; i < 11; ++i) {
        websocket.send(i.toString());
    }
    console.log("Connected to WebSocket server.");
};

websocket.onclose = function (evt) {
    console.log("Disconnected");
};

websocket.onmessage = function (evt) {
    console.log('Retrieved data from server: ' + evt.data);
};

websocket.onerror = function (evt, e) {
    console.log('Error occured: ' + evt.data);
};
</script>
HTML
    );
});

$server->start();
```

2. What did you expect to see?

repeat ```Ping```

3. What did you see instead?

```
server: handshake success with fd2
receive from 2:0,opcode:1,fin:1
receive from 2:1,opcode:1,fin:1
receive from 2:2,opcode:1,fin:1
receive from 2:3,opcode:1,fin:1
receive from 2:4,opcode:1,fin:1
receive from 2:5,opcode:1,fin:1
receive from 2:6,opcode:1,fin:1
receive from 2:7,opcode:1,fin:1
receive from 2:8,opcode:1,fin:1
receive from 2:9,opcode:1,fin:1
receive from 2:10,opcode:1,fin:1
```
without ```Ping```, It seems that server->tick was not called
4. What version of Swoole are you using (show your `php --ri swoole`)?

4.2.8

5. What is your machine environment used (including version of kernel & php & gcc) ?

PHP 7.1.20, gcc 4.2.1, kernel Darwin Kernel Version 17.7.0

**Comment by yueyuzhao** [comment]
If we change max_request to 11 or other numbers that greater than 10, ticker will run correctly.

**Comment by flddr** [comment]
Can you please explain what you are trying to archive? ☺️ 

Doing `'max_request' => 10,` is not really useful in your case?

If you do

```js
websocket.onopen = function (evt) {
    for (var i = 0; i < 11; ++i) {
        websocket.send(i.toString());
    }
    console.log("Connected to WebSocket server.");
};
```

and

```php
$server->on('message', function (Swoole\WebSocket\Server $server, $frame) {
    echo "receive from {$frame->fd}:{$frame->data},opcode:{$frame->opcode},fin:{$frame->finish}\n";
    $server->push($frame->fd, "this is server");
});
```

you will get

```bash
receive from 2:0,opcode:1,fin:1
receive from 2:1,opcode:1,fin:1
receive from 2:2,opcode:1,fin:1
receive from 2:3,opcode:1,fin:1
receive from 2:4,opcode:1,fin:1
receive from 2:5,opcode:1,fin:1
receive from 2:6,opcode:1,fin:1
receive from 2:7,opcode:1,fin:1
receive from 2:8,opcode:1,fin:1
receive from 2:9,opcode:1,fin:1
receive from 2:10,opcode:1,fin:1
```

and reach `'max_request' => 10,`, which does as explained:

-------------------
https://wiki.swoole.com/wiki/page/p-max_request.html

Max_request
Set the maximum number of tasks in the worker process. The default is 0. A worker process will automatically exit after processing a task that exceeds this value. All memory and resources will be released after the process exits.

The main role of this parameter is to solve the PHP process memory overflow problem . The PHP application has a slow memory leak, but it cannot be located for specific reasons and cannot be max_requestresolved. It can be solved by setting .

max_requestCan only be used for synchronous blocking, stateless request-responsive server programs
The real process of maintaining the client TCP connection in the swoole is the master process, and the worker process only processes the request sent by the client, because the client does not need to perceive the worker process to restart.
Pure asynchronous server should not be setmax_request
max_requestInvalid when using Base mode
When a fatal error or manual execution exitoccurs within the worker process , the process automatically exits. The master process will restart a new worker process to continue processing the request.

**Comment by yueyuzhao** [comment]
@flddr Many thanks for your detail explanation. I think you are absolutely right that the worker process automatically exits after processing a task that exceeds this value. I wrongly thought that websocket workers are not affected by ```max_request```.
