### ISSUE TITLE
macOS Mojave "/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace"

### ISSUE THREAD

**Issue by ofttryaj** [swoole/swoole-src#2503]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

make

2. What did you expect to see?

make通过

3. What did you see instead?

macOS Mojave "/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace"

4. What version of Swoole are you using (show your `php --ri swoole`)?

swoole4.3.1

5. What is your machine environment used (including version of kernel & php & gcc) ?

mac os Mojave 
![image](https://user-images.githubusercontent.com/15887451/56073459-d33ebf00-5dd6-11e9-9256-4cbd28472b67.png)

**Comment by dixyes** [comment]
看起来像是使用的cc(c++)与编译使用的头不是一同提供的（例如使用了自行编译的新版本llvm-clang中的cc(c++)配合系统的头）导致了玄学问题。
建议检查头文件包含路径，在Makefile手动修改，尝试编译。
顺便请提供完整的出错的信息（from which file），configure配置（记录在config.nice)

This error may occur due to different provider of headers and compiler. (for example: using llvm-clang compiled from source and system providen headers.)
You may try edit Makefile manually and try to make again.
P.S. Please provide full stack info of error(from which file) and configuration. (will be logged into config.nice)

**Comment by ofttryaj** [comment]
phpize: 
[phpize.txt](https://github.com/swoole/swoole-src/files/3078544/phpize.txt)
configure: 
[configure.txt](https://github.com/swoole/swoole-src/files/3078545/configure.txt)
make:
[make.txt](https://github.com/swoole/swoole-src/files/3078546/make.txt)
@dixyes 帮忙看下，谢谢！

**Comment by matyhtf** [comment]
无法重现。建议检查环境。
