### ISSUE TITLE
WebRTC streaming with Swoole

### ISSUE THREAD

**Issue by pthreat** [swoole/swoole-src#2828]
This is just a question, if it doesn't belongs here please let me know where should I add it.
Thank you!

4. What version of Swoole are you using (show your `php --ri swoole`)?

4.4.5

5. What is your machine environment used (including version of kernel & php & gcc) ?

Linux 79755ba2f089 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

gcc (Debian 8.3.0-6) 8.3.0

PHP 7.2

--- 

I'd like to know how could I achieve streaming through WebRTC with swoole since I haven't seen any examples for it.

Thanks!

**Comment by need-sleep** [comment]
Hello, since nobody has answered this I will. Swoole currently has no support for WebRTC and I don't think it is likely that it will ever have full WebRTC support. While basic DataChannels can be created over SCTP and MediaChannels can be created over SRTP, "full" WebRTC also requires SDP, ICE, STUN, etc, and full WebRTC support also requires media access. And to provide a useful server side experience it will also require hooking into libraries to process media such as gstreamer and/or ffmppg.

**Comment by need-sleep** [comment]
Also, existing WebRTC server projects such as Mediasoup and Janus provide ways to use with plaftorms such as Swoole via Unix Domain Sockets and other IPC based mechanisms.

**Comment by pthreat** [comment]
Alright, thanks for the response!
