### ISSUE TITLE
Developer chat

### ISSUE THREAD

**Issue by Atriedes** [swoole/swoole-src#312]
Hi,

I would like to contribute to English translation of this project, I will start translating swoole API doc but Im afraid that Im missed something important for the docs since I cant read/write Chinese. I think its better to have developer/user chat application like gitter.im, irc, or slack.

Also I tried my best to promote this project, next week Im going to talk about swoole in my local user group and hopefully it can attract more developer to contribute to this project

Thanks!

**Comment by yangchaogit** [comment]
:), Welcome ! Thks for you contribution. We have already build a doc project here !


https://github.com/swoole/swoole-doc, you should clone this project and edit doc here and push it back.


You can also refer this :http://wiki.swoole.com/one by one.


You had better join the wechat group , install wechat(http://weixin.qq.com/) on your mobile, then scan the QR below.


If you have any question, let’s chat here.






原始邮件
发件人:Prasetyonotifications@github.com
收件人:swoole/swoole-srcswoole-src@noreply.github.com
发送时间:2015年7月16日(周四) 00:06
主题:[swoole-src] Developer chat (#312)


Hi,
I would like to contribute to English translation of this project, I will start translating swoole API doc but Im afraid that Im missed something important for the docs since I cant read/write Chinese. I think its better to have developer/user chat application like gitter.im, irc, or slack.
Also I tried my best to promote this project, next week Im going to talk about swoole in my local user group and hopefully it can attract more developer to contribute to this project
Thanks!

**Comment by yangchaogit** [comment]
![1 pic](https://cloud.githubusercontent.com/assets/5636922/8704155/e013108c-2b53-11e5-847f-b19e3659ccd4.jpg)

**Comment by Atriedes** [comment]
Hi,

Thanks I have already cloned that repo ;)and I'm in the middle of translation process (using google translate) and hopefully it will accurately translated :)

**Comment by Atriedes** [comment]
@matyhtf : I just created IRC channel for swoole, please add it to you erbsite and this read me

here is the channel:

#swoole at freenode

See you in IRC :)

**Comment by matyhtf** [comment]
Ok, see you later. :)
