### ISSUE TITLE
what's the scope of a outer var used by callback 

### ISSUE THREAD

**Issue by scil** [swoole/swoole-src#322]
like var $abc, which is used by OnRequest callback.

```
<?php
$http = new swoole_http_server("0.0.0.0", 9501);

$http->set(
			array(
				'worker_num' => 4,
				'daemonize' => false,
	            'max_request' => 1000,
	            'dispatch_mode' => 1
			)
		);

$abc=[];

$http->on('request', function ($request, $response) use(&$abc) {

    if(isset($abc['obj'])){
        echo "\n".'old';
    }else{
        $abc['obj']=new stdClass();
        $abc['obj']->age= rand(1000, 9999);
        echo "\n".'new';
    }
   $age=$abc['obj']->age;
    echo $age;
});


$http->start();
```

I start this server and visit 127.0.0.1:9501, and get following 
```

new
1771

new
3045

old
1771

old
3045

old
1771

old
3045

old
1771

old
3045

new
4466

new
7229

old
4466

old
3045

old
1771

old
3045

old
1771

old
3045


```

there are four numbers and appear repeatedly,

does $abc exists in worker scope or reactor scope?

**Comment by Atriedes** [comment]
$abc exist in worker,

it is repeated 4 times because you set dispatch mode to 1 it means worker manager using roundrobin technique to dispatcher request to worker.

you can read here but its incomplete yet : https://github.com/swoole/swoole-doc/blob/master/docs/en/server/set.md

here is my result of your code

dispatch mode 1

```
new4549
new9999
new2608
new1609
old4549
old9999
old2608
old1609
old4549
old9999
old2608
old1609
old4549
old9999
```

as you see the pattern is round robin

and this is result of dispatch mode 2

```
new2353
old2353
old2353
old2353
old2353
old2353
old2353
old2353
old2353
old2353
old2353
```

It shows your request handled by same worker

I hope its help :)

**Comment by scil** [comment]
Thank you very much!
