### ISSUE TITLE
Typo, VEFIRY instead of VERIFY 

### ISSUE THREAD

**Issue by robertbakker** [swoole/swoole-src#3237]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I see "vefiry" coming up instead of "verify" e.g. SWOOLE_ERROR_SSL_VEFIRY_FAILED
and error message 
```
case SW_ERROR_SSL_VEFIRY_FAILED:
        return "SSL vefiry failed";
```

in -> https://github.com/swoole/swoole-src/blob/master/src/core/error.cc
and -> https://github.com/swoole/swoole-src/blob/master/tests/swoole_http_client_coro/ssl_verify_peer_1.phpt

2. What did you expect to see?

SWOOLE_ERROR_SSL_VERIFY_FAILED

3. What did you see instead?

SW_ERROR_SSL_VEFIRY_FAILED

4. What version of Swoole are you using (show your `php --ri swoole`)?

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.0RC1

5. What is your machine environment used (including version of kernel & php & gcc) ?

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs
