### ISSUE TITLE
Does Swoole Coroutine use CPU multicore?

### ISSUE THREAD

**Issue by a6965921** [swoole/swoole-src#3548]
Does Swoole Coroutine use CPU multicore?

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by huanghantao** [comment]
Swoole Coroutine is not. The context for Swoole is currently switching within the same thread.

**Comment by a6965921** [comment]
> Swoole Coroutine is not. The context for Swoole is currently switching within the same thread.

Now the single frequency of the host is so low  i feel can't Give full play to advantages

**Comment by twose** [comment]
Swoole is a multi-process model

Just like Nginx, Redis, NodeJS
