### ISSUE TITLE
ssl协议内存错误

### ISSUE THREAD

**Issue by z5864703** [swoole/swoole-src#3765]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
升级到4.5.5版本后，四台服务器其中一台出现这个问题，四台服务器环境都一致。
通过搜索double free or corruption关键词，看起来似乎是代码内存操作相关问题

2. What did you expect to see?
正常运行

3. What did you see instead?

![image](https://user-images.githubusercontent.com/15603173/96968075-02dd9400-1543-11eb-8568-b9c2e03d3a63.png)

还有另外一个问题，升级到4.5.3之后一直出现的，资源不可用？看起来是master和worker管道通信的问题

![image](https://user-images.githubusercontent.com/15603173/96968417-8a2b0780-1543-11eb-8425-f0b1ea0e7dbb.png)

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.5
Built => Oct 15 2020 16:25:34
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
PHP 7.3.22 (cli) (built: Sep 28 2020 15:58:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.22, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.22, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by twose** [comment]
**[自动回复] 为了中文搜索引擎收录以便于后人检索和Github各国友人参与理解所需，本repo只接受英文issue**

**中文issue请前往[Swoole中文问答社区](https://wenda.swoole.com/)**

**谢谢合作!**

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by z5864703** [comment]
@twose @huanghantao @matyhtf
