### ISSUE TITLE
Problems using Process modules in the Coroutine environment

### ISSUE THREAD

**Issue by Alion548** [swoole/swoole-src#3803]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
``` php
<?php
\Co\run(function () {
    $process = new swoole_process(function (swoole_process $process) {
        $process->exec('/bin/sleep', ['999']);
    }, true, 0, false);

    $process->start();
});
```
2. What did you expect to see?
The code is problematic because the fork process carries other Coroutine contexts within the concatenation space, so the bottom line prohibits the use of the Process module in Coroutine, but I'm only calling the exec function in the child process, so that would overwrite the child process code segment, so wouldn't that be fine?

I commented out that code and it works fine now, is there a potential problem?
https://github.com/swoole/swoole-src/blob/5cc784cbc5c2b5f163c0fe960f8a74ab3ec20961/src/core/base.cc#L247-L249

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by sy-records** [comment]
see https://wiki.swoole.com/#/coroutine/proc_open?id=%e5%8d%8f%e7%a8%8b%e8%bf%9b%e7%a8%8b%e7%ae%a1%e7%90%86

**Comment by Alion548** [comment]
There is a problem with the HOOK function of proc_open, which directly causes the program to exit when a SIGCHLD event has been registered.
```php
Swoole\Process::signal(SIGCHLD, function() {
    while ($process = Swoole\Process::wait(false)) {
        var_dump($process);
    }
});

$proc = proc_open('/bin/sleep 1000', $descriptorspec, $pipes);
var_dump($proc); //false
```
``` bash
The signal [SIGCHLD] is registered, cannot execute swoole_proc_open
```

**Comment by sy-records** [comment]
Can you try it with the latest release?

![image](https://user-images.githubusercontent.com/33931153/97843339-1992a080-1d24-11eb-82e1-b8286d4fef53.png)

**Comment by Alion548** [comment]
Please try the full code.

```php
<?php

\Co::set(['hook_flags' => SWOOLE_HOOK_PROC]);

Swoole\Process::signal(SIGCHLD, function() {
    while ($process = Swoole\Process::wait(false)) {
        var_dump($process);
    }
});

Co\run(function () {
    $descriptorspec = array(
        0 => array("pipe", "/dev/null"),
        1 => array("pipe", "/dev/null"),
        2 => array("pipe", "/dev/null")
    );

    $proc = proc_open('/bin/sleep 1000', $descriptorspec, $pipes);
    var_dump($proc); //false
});
```
```shell
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.6
Built => Nov  2 2020 04:57:25
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1g FIPS  21 Apr 2020
http2 => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by sy-records** [comment]
you can use `Swoole\Coroutine\System::waitSignal` https://wiki.swoole.com/#/coroutine/system?id=waitsignal

**Comment by matyhtf** [comment]
`Swoole\Process::signal` is deprecated, that is an asynchronous callback style API.

You should use `proc_close` to wait for the process to exit

**Comment by Alion548** [comment]
> `Swoole\Process::signal` is deprecated, that is an asynchronous callback style API.
> 
> You should use to wait for the process to exit.`proc_close`
> 
> ```
> <?php
> \Co::set(['hook_flags' => SWOOLE_HOOK_PROC]);
> 
> Co\run(function () {
> 
>     $descriptorspec = array(
>         0 => array("pipe", "/dev/null"),
>         1 => array("pipe", "/dev/null"),
>         2 => array("pipe", "/dev/null")
>     );
> 
>     $proc = proc_open('/bin/sleep 1000', $descriptorspec, $pipes);
>     var_dump($proc); //false
>     echo "wait begin\n";
>     proc_close($proc);
>     echo "wait end\n";
> });
> ```

What if I want asynchronous signal monitoring, or don't want to blocking the code?
