### ISSUE TITLE
Swoole warnings and notices in the log. Difficult to localize the problem

### ISSUE THREAD

**Issue by idealogica** [swoole/swoole-src#3826]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

I'm running a kind of TCP proxy using Swoole async server and coroutine client.
I'm getting a LOT of the following notice messages on the log:

`NOTICE  swFactoryProcess_end (ERRNO 1003): The connection[3443189] is closing`

Also quite often the following:

```
[2020-11-09 08:11:42 #30776.5]  NOTICE  send_to_connection (ERRNO 1005): send event[3] failed, session#3509712 does not exist
[2020-11-09 08:11:46 #30776.7]  NOTICE  send_to_connection (ERRNO 1005): send event[3] failed, session#3510901 does not exist
[2020-11-09 08:11:53 #30776.5]  NOTICE  send_to_connection (ERRNO 1005): send event[3] failed, session#3513644 does not exist
[2020-11-09 08:11:59 #30776.1]  NOTICE  send_to_connection (ERRNO 1005): send event[3] failed, session#3516062 does not exist
[2020-11-09 08:12:07 #30776.2]  NOTICE  send_to_connection (ERRNO 1005): send event[3] failed, session#3518521 does not exist
[2020-11-09 08:12:10 $30777.0]  WARNING check_worker_exit_status: worker#11[pid=8406] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.5, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

or

```
[2020-11-09 07:18:35 *2644.10]  NOTICE  swFactoryProcess_end (ERRNO 1003): The connection[2215734] is closing
[2020-11-09 07:18:35 *2644.10]  NOTICE  swFactoryProcess_end (ERRNO 1003): The connection[2216320] is closing
[2020-11-09 07:18:35 *2644.10]  NOTICE  swFactoryProcess_end (ERRNO 1003): The connection[2216294] is closing
[2020-11-09 07:18:38 *2644.10]  NOTICE  swFactoryProcess_end (ERRNO 1003): The connection[2217496] is closing
[2020-11-09 07:18:38 $30777.0]  WARNING check_worker_exit_status: worker#29[pid=4671] abnormal exit, status=0, signal=11
A bug occurred in Swoole-v4.5.5, please report it.
The Swoole developers probably don't know about it,
and unless you report it, chances are it won't be fixed.
You can read How to report a bug doc before submitting any bug reports:
>> https://github.com/swoole/swoole-src/blob/master/.github/ISSUE.md
Please do not send bug reports in the mailing list or personal letters.
The issue page is also suitable to submit feature requests.
```

I'm not sure how to localize and fix the errors. Can you give some hints? 
Thank you!

2. What did you expect to see?

No warnings and notices in the log.

3. What did you see instead?

Mentioned warnings and notices in the log.

4. What version of Swoole are you using (show your `php --ri swoole`)?

```
php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.5.5
Built => Nov  6 2020 18:38:27
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g  21 Apr 2020
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

```
Linux host.name 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
PHP 7.4.12 (cli) (built: Oct 31 2020 17:04:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologies
```

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by twose** [comment]
[Robot]: Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by idealogica** [comment]
The mentioned messages are shown only on production environment. I guess valgrind log will be very big on production env because of a lot of concurrent connections. Is there a way to use it on production?

**Comment by doubaokun** [comment]
@idealogica Could you find me on Slack?

**Comment by idealogica** [comment]
Just contacted...

**Comment by idealogica** [comment]
@doubaokun Just contacted...

**Comment by lclkLWJ** [comment]
have you fix the problem？

**Comment by lclkLWJ** [comment]
have you fix the problem？
