### ISSUE TITLE
swoole tracker error

### ISSUE THREAD

**Issue by lg430** [swoole/swoole-src#3834]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
```
swoole tracker return empty while /tmp/valgrind.log more than 100M

wenda url:
https://wenda.swoole.com/detail/107620
```

4. What version of Swoole are you using (show your `php --ri swoole`)?
php 7.4.12
swoole 4.5.7
swoole_tracker 3.03
OpenSSL 1.1.1h 

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Linux  4.18.20-1.el7.x86_64 #1 SMP Fri Aug 16 10:58:52 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by sy-records** [comment]
Please direct feedback on swoole issues, not tracker issues.

Thank you for your BUG feedback. Please quickly confirm the following points to help us locate your problem:

1. If you upgraded manually instead of compiling for the first time, make sure you run `make clean` before compiling to clean up the contents of the last compilation

2. If you are using a Linux, use the following command to run your program, operate your program in a way that can reproduce the bug, and show the content of valgrind.log in the /tmp dir after the program runs for a certain time

```shell

USE_ZEND_ALLOC=0 valgrind --log-file=/tmp/valgrind.log php xxx.php

```

3. If you are using macOS, you will not be able to use valgrind, please provide PHP code that can reproduce the bugs

**Comment by lg430** [comment]
@sy-records 
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 28672 bytes) in @tracker-src/library/tracker/Leak.php on line 112

**Comment by sy-records** [comment]
uninstall swoole_tracker, replicate your problem and use valgrind tracking.

**Comment by lg430** [comment]
$ php -i|grep memory_limit
memory_limit => 256M => 256M

so, i change the code and it works
```
php -r "ini_set('memory_limit', '1024M'); trackerAnalyzeLeak();"  
```

**Comment by lg430** [comment]
may be, it can optimize memory of file io ?

**Comment by twose** [comment]
it looks like the tracker needs more memory to store trace-data, not like a bug.
