### ISSUE TITLE
Any plan to make full pledged php server with swoole?

### ISSUE THREAD

**Issue by yellow1912** [swoole/swoole-src#3894]
This is not an issue but just a general interest in the direction of swoole? Right now most php setup comes with: 
1. Web server such nginx 
2. Process manager such as php-fpm

The problem is that this setup is often clunky, and php-fpm is often a real bottle neck. Right now we are seeing some candidates:

1. Php-pm: runs on reactphp I think? This is a pure php solution which yields some promising results. It's not as fast as it can be however, and seems to have some issues.
2. Roadrunner: written in go, looks very promising as well. The only drawback (for me) would be that it's Go. I coded in Go before, but not a big fan.

It would be nice if we write something in swoole that supports basic php (full psr7) server? What is the drawback? Stability? Performance? I see swoole is having some issues with ssl for example?

**Comment by matyhtf** [comment]
I don't understand what you mean, The `Swoole\Http\Server` provides a complete http server implementation. 

You can list the specific features you want ?

**Comment by microerror** [comment]
> The problem is that this setup is often clunky, and php-fpm is often a real bottle neck

What's "clunky" about it? You have nginx that can proxy to a pool of php-fpm servers. 

If 1 nginx server can process 10k requests a second and 1 php-fpm server can process 200 requests per second, maths is easy in this case and you can calculate how many php-fpm servers you need to provide 10k req/sec.

That's the basics of scaling, use the web server to distribute the load to php-fpm's. Using nginx's `upstream`, this becomes easy to manage and now you can scale your php-fpm fleet horizontally.

Change php-fpm for nodes that run on swoole instead, you get the same scalability but better I/O + CPU usage due to swoole's async support.

Nginx is a powerful server, and for any serious app you resort to horizontal scaling instead of changing the runtime and wasting development time on squeezing out bits of performance. 

Anything that uses PHP command line to start a server won't get close to swoole - not something based on reactphp, not the go solution you mentioned (it's false marketing anyway, it sucks and sucks heavily). Reason is: they don't have the means to perform async I/O the way swoole does it, and waiting for I/O to complete is one of PHP's pain points and reasons for performance degradation.

Using swoole as the web server that's facing public comes with series of problems - not all devops are familiar with swoole. How do you scale horizontally? How do you deal with SSL termination and certificate updates?

It makes more sense to use nginx as the balancer / ssl terminator and to scale to a fleet of nodes based on swoole. This way, you don't need to depend on software that's not yet finished and you're using tools that have established their presence in world of IT (namely: nginx).

Or, you can ignore what's been written and spend your valuable time as a developer (measured in thousands of dollars a month) in order to slightly optimize hardware performance that costs tens of dollars a month.

**Comment by Socengel** [comment]
> It would be nice if we write something in swoole that supports basic php (full psr7) server? What is the drawback? Stability? Performance?

As its not discribed above, main thing of not to implement any recomendations (PHP Standart Recomendations) because its not about perfomance (C needed only for perfomance), Its about logic to work with something. If this will be implemented in swoole and after year or two this recomendation will be obsoleted by theoretical PSR-27 (whitch is possible) there will be huge pain to remove this from both sides instead of just rewrite user code when you have time for this or doesn't rewrite it at all ;) . So PSR is a userland story, we can write competitive implementations (Performance, RFC compability or both) by themselves and swoole provides all what is needed for this.

**Comment by doubaokun** [comment]
> It would be nice if we write something in swoole that supports basic php (full psr7) server? What is the drawback? Stability? Performance? I see swoole is having some issues with ssl for example?

You should be able to run PSR7 applications with Swoole. Just have to make sure the variable are used as expected; convert the request and response objects.

There will be more native support regarding PSR in the future.
