### ISSUE TITLE
Feature request: Permit raw HTML in swoole

### ISSUE THREAD

**Issue by jobs-git** [swoole/swoole-src#3945]
The main issue I encountered with swoole is that it wants all HTML as string, however, we loose code hinting and syntax highlighting.

**Comment by Socengel** [comment]
`ob_start();
include 'external/html/file.html';
$string = ob_get_clean();`

you can even use $this or context variables in external file... 
P.S. this is not "stackoverflow"...

**Comment by jobs-git** [comment]
That is funny, feature request are not done in stuckoverflow.

Tnx for this code
```
ob_start(); include 'external/html/file.html'; $string = ob_get_clean();
```
That indicates that this feature is not yet in place.

**Comment by Socengel** [comment]
Code i wrote works since php4 and ALL major frameworks and php template engines uses this behavior nowdays.
Also when you call ob_start() it disables usage of STDOUT stream whitch makes a huge performance boost. Otherways if you NOT use this code, you will get huge perfomance downgrade...
So your feature request is posiibility to performance downgrade? ob_get_* functions  (except for length and level) returns only strings and this is all what is needed. 

**Zend** - https://github.com/zendframework/zend-view/blob/1b8c1896e47a2f6179f0369a96c4072e1cb39ee8/src/Renderer/PhpRenderer.php#L505
**Symphony** - https://github.com/symfony/symfony/blob/494ef421c554a78b38c6779c4b7deb9a20d89923/src/Symfony/Component/Templating/PhpEngine.php#L144
**Twig** - https://github.com/twigphp/Twig/blob/e54fe12355223bca75ddb08e04a3cbd172eaf280/src/Template.php#L236
**Codeigniter** - https://github.com/bcit-ci/CodeIgniter/blob/18718545e0faa98d62df3f65d045d84494ec29ca/system/core/Loader.php#L958
**CakePhp** - https://github.com/cakephp/cakephp/blob/b6800b33e19f7204b500465e46eecd6fa30388b2/src/View/ViewBlock.php#L94

**Comment by matyhtf** [comment]
You should use ob_* functions to capture the content and output to a string
