### ISSUE TITLE
Are there plans to natively support Windows at some point ?

### ISSUE THREAD

**Issue by not-a-lot** [swoole/swoole-src#4289]
Hi, I’ve read that on Windows, we have to use Cygwin, WSL or Docker. I’d like to know if Windows is not directly supported for Swoole because of a lack of interest and time from the developers, or is it technically not possible at all to make it work on Windows (same kind of reason why PHP-FPM is not available on Windows, for example) ? Will support for Windows come later ? Thank you

**Comment by twose** [comment]
Swoole has no plan to natively support Windows, because it uses many Linux only features, this makes it perform very well on Linux, but this also makes it difficult to port it to Windows. Just like Docker can only rely on virtual machines to run on non-Linux platforms, because it uses many linux-only features too.

[Swow](https://github.com/swow/swow)  is a new project that is still under actively development, it provides functions similar to Swoole and supports all major operating systems, you can download Windows DLL from [here](https://github.com/swow/swow/releases) directly.
