### ISSUE TITLE
./configure: line 6044: syntax error near unexpected token `-Wbool-conversion,'

### ISSUE THREAD

**Issue by laocc** [swoole/swoole-src#4416]
PHP 7.2.6 (cli) (built: Apr 26 2019 16:08:00) ( NTS )
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

要升级到swoole-src-4.7.1（现在是4.5.0）
./configure --with-php-config=/usr/local/php/bin/php-config --enable-openssl
后出错：
```
checking if compiling with clang... no
checking for cc option to accept ISO C99... -std=gnu99
./configure: line 6044: syntax error near unexpected token `-Wbool-conversion,'
./configure: line 6044: `        AX_CHECK_COMPILE_FLAG(-Wbool-conversion,                _MAINTAINER_CFLAGS="$_MAINTAINER_CFLAGS -Wbool-conversion")'
```

**Comment by twose** [comment]
看看
`which phpize`
`which php-config`
`phpize --version`
`php-config --version`
`/usr/local/php/bin/phpize --version`
`/usr/local/php/bin/php-config --version`

**Comment by matyhtf** [comment]
编译参数去掉：`--enable-swoole-dev`

**Comment by petk** [comment]
Hello,

this is most likely one of the dependencies issue here from the PHP build system. Rebuild the Swoole extension with PHP version 7.3 or newer, because there were many changes in the build system since then.

Besides, PHP 7.2 is [not supported anymore](https://www.php.net/supported-versions.php).

**Comment by duan1v** [comment]
same question.
due to multiple versions of PHP in my env,
php -v , see php7.4
but phpize ,see 20131106
then `sudo apt-get install php7.4-dev` (unnecessary maybe)
try `phpize7.4`
--------------------------------------------
when `make -j 4`, encount another question,"error: ‘zend_class_serialize_deny’ was not declared in this scope; did you mean ‘zend_ce_serializable’?"
then i redo `./configure` with specific php-version ,like `./configure --with-php-config=/usr/bin/php-config7.4`
--------------------------------------------
then `make -j 4` ,encount another one ,"fatal error: curl/curl.h: No such file or directory 25 | #include <curl/curl.h>"
due to `./configure --enable-openssl`
then `sudo apt-get install libcurl4-openssl-dev` and  `make -j 4`

ok~
