### ISSUE TITLE
[Question] Postgres is blocking

### ISSUE THREAD

**Issue by foremtehan** [swoole/swoole-src#4573]
Excuse me i'm using v4.8.3, Does this PR released ? https://github.com/swoole/swoole-src/pull/4467

Postgres still is blocking for me, Does upgrading to 4.8.6 helps?

**Comment by leocavalcante** [comment]
Are you using the extension code, the `Swoole\Coroutine\PostgreSQL` or are you connecting to Postgres through PDO?

**Comment by foremtehan** [comment]
I'm using swoole extension via https://github.com/cachewerk/heroku-php-extensions for laravel octane which uses PDO for postgress if i'm not wrong

**Comment by foremtehan** [comment]
I tested it my self:

```
Class "Swoole\Coroutine\PostgreSQL" not found
```

**Comment by leocavalcante** [comment]
Unfortunately, Swoole can't hook `pdo_pgsql` like it does for `pdo_mysql` (under `mysqlnd`).
To use non-blocking Postgres, instead of PDO, you need to use the API provided by the Swoole's `ext-postgresql`.

Not sure if it is possible to create new drivers for Laravel's Eloquent ORM, but for Doctrine, for exemple, you can try https://github.com/leocavalcante/swoole-postgresql-doctrine-driver

It is not a Laravel issue, but pinging @taylorotwell @driesvints @GrahamCampbell @nunomaduro and @themsaid to check the possibility of us creating such a library that can transparently replace PDO by another Driver for Eloquent users.

**Comment by foremtehan** [comment]
what is the diff between `ext-postgresql` vs [this PR](https://github.com/swoole/swoole-src/pull/4467) ? I thought they merge the `ext-postgresql` into swoole code base

**Comment by leocavalcante** [comment]
The merge is on `master`, not in the `4.8.x` branch. You have to compile Swoole from there with `--enable-swoole-pgsql` option.

But even if it does, remember that you will still need to use `\Swoole\Coroutine\PostgreSQL` instead of `\PDO`.
