### ISSUE TITLE
Translate to English?

### ISSUE THREAD

**Issue by patlecat** [swoole/swoole-src#4824]
What about translating your website to English (swoole.com)? How else would we know what your products do and why we should buy them?

**Comment by leocavalcante** [comment]
@deminy
How `swoole.dev` ended up?

@matyhtf 
Forking + PR to https://github.com/swoole/docs with a `en/` directory would be a good way to go?

**Comment by deminy** [comment]
I don't think @matyhtf or other active team members has enough spare time to work on it.

> Forking + PR to https://github.com/swoole/docs with a en/ directory would be a good way to go?

Yep. And, it would be great if there is someone to volunteer to maintain the Git repository or take ownership of it.

**Comment by leocavalcante** [comment]
@deminy, where https://github.com/swoole/docs is rendered?

**Comment by deminy** [comment]
@leocavalcante Sorry I don't know.

I assume that there is a private Git repository to render site [https://wiki.swoole.com/](https://wiki.swoole.com/), which is not maintained by the Swoole team on GitHub. GitHub repository https://github.com/swoole/docs was created as a public repository, and had existing documentation copied from that private Git repository. This allows anyone to contribute to the documentation (as you said, by forking + PR), and to have an international documentation site running in the future.

**Comment by sy-records** [comment]
The swoole documentation uses [docsify](https://github.com/docsifyjs/docsify), but the current [swoole/docs](https://github.com/swoole/docs) needs some modifications to get it to work properly.

**Comment by AdamSGit** [comment]
It would be good to set up the doc from a public repository that can be translated in multiple languages by the community. I would get involved if it was the case. Swoole could shine a lot more in the PHP community if more ressources were accessible in english, at least.

**Comment by matyhtf** [comment]
@AdamSGit Thanks for your suggestion, I haven't much idle time to write documentation lately. It is planned to start the English document project in July 2023

**Comment by leocavalcante** [comment]
@matyhtf, count on me for any help!

**Comment by AdamSGit** [comment]
Great ! Maybe I can start ahead. Can you confirm that the up-to-date source of wiki.swoole.com is the repo swoole/docs ?

I was thinking to have the docsify setup directly in that repo, along with all locales. That would allow to make multilanguage doc changes directly in this repo, that could also be automatically deployed on merge using github pages.

For the translation itself, i made some test, and Deepl seem to do a good job at translating markdown from mandarin to english. It is also cheap, like 25$ the 1.000.000 characters. Swoole doc markdown files contain 620.680 chars, which would be under 20$. I can take care of it if you want. It may require some proofreading from people that known swoole and the swoole doc well tho.

Also, another thing in the same topic : I noticed that some issues in this repo are written in mandarin only, which can make it difficult to search in for non chinese people. I noticed that a [https://github.com/marketplace/actions/issues-translator](github action) does automatic issue translation. It seem quite easy to setup. Do you want me to do a PR for that ?

**Comment by AdamSGit** [comment]
Up 👋

The last activity in this issue is almost a year old. Any advancements on this ? I am still motivated to translate the doc. @matyhtf Can you give me some access to the place where I can find the up to date documentation so I can set up a translation process ?

I may be involded with setting a public repository for the doc that could accept PR regarding content translations and corrections.

**Comment by leocavalcante** [comment]
https://github.com/swoole/docs seams active. Maybe a `en` directory there looks like a starting point?

**Comment by AdamSGit** [comment]
I already started to setup the automated translating process, but make it done will take me some time and a few bucks. 

So before I do it, and since the doc translation question is on the table for years without any real progress I would like to make sure of the following points, I don't know if you can answer @leocavalcante  : 

- If I get the work done, is the core team motivated to deploy it in a reasonable timeframe ?
- The swoole/doc repo may look active, but is it the up-to-date one that is the source of wiki.swoole.com ?
- Either its yes or no, are you satisfied with the current docsify environment ? Since I work on it, I could also modernise it with more moderns tools such as vitepress

Thanks

**Comment by matyhtf** [comment]
https://wiki.swoole.com/en/#/
