### ISSUE TITLE
Memory leak in Laravel Octane when running in `SWOOLE_BASE` mode 

### ISSUE THREAD

**Issue by smortexa** [swoole/swoole-src#5142]
There seems to be a memory leak issue with Laravel Octane when using SWOOLE_BASE mode. I am not aware of any recent PRs that specifically tackle this problem.

After switching from SWOOLE_PROCESS mode to SWOOLE_BASE mode, there is a noticeable change in the pattern of memory usage:

![image](https://github.com/swoole/swoole-src/assets/47121888/c89e65fb-e93a-43c0-8b5b-b9ae8728576f)

**Comment by leocavalcante** [comment]
Maybe closed by https://github.com/swoole/swoole-src/pull/5134

**Comment by matyhtf** [comment]
a few suggestions

1. A lot of data is stored in global variables and static variables, which leads to an increase in the memory usage of the process. Check whether there is an operation in the code that adds elements to the global variables without releasing them
2. ZendVM did not reclaim memory in time, you may need to call gc_collect_cycles regularly, or you can try to use jemalloc or tcmalloc instead of zend mm
3. Set MaxRequest, after processing enough requests, let the worker process exit and release the memory
4. Use k8s and other deployment tools to control the life cycle of the pod so that it does not run for too long
