### ISSUE TITLE
real_escape_string not accept numbers

### ISSUE THREAD

**Issue by LaySoft** [swoole/swoole-src#5639]
If real_escape_string method using with connection handler provided by MysqliPool, and the method parameter is number, the following error occured:

`Fatal error: Uncaught TypeError: mysqli::real_escape_string(): Argument #1 ($string) must be of type string, int given in @swoole/library/core/Database/MysqliProxy.php:50`

**Comment by LaySoft** [comment]
The original mysql_real_escape_string works with numbers:
```
$conn = mysqli_connect(MYSQL_HOST, MYSQL_USER, MYSQL_PASS, MYSQL_DB, MYSQL_PORT);

echo mysqli_real_escape_string($conn, 123);
```
But with the Swoole pool connection not:
```
use Swoole\Database\MysqliConfig;
use Swoole\Database\MysqliPool;

$config = (new MysqliConfig())
	->withHost(MYSQL_HOST)
	->withPort(MYSQL_PORT)
	->withUsername(MYSQL_USER)
	->withPassword(MYSQL_PASS)
	->withDbName(MYSQL_DB)
	->withCharset('utf8mb4');

$pool =  new MysqliPool($config, 5);

Co\run(function() use ($pool) {
	Co\go(function() use ($pool) {
		$conn = $pool->get();
		echo $conn->real_escape_string('456');
		echo $conn->real_escape_string(789);
	});
});
```
The first echo shows '456', but the second throws a fatal error.

**Comment by matyhtf** [comment]
@LaySoft This is because strict mode is enabled in the Swoole code. Try adding `declare(strict_types=1);` at the top of your file.

Please refer to the PHP documentation for the mysqli_real_escape_string function: https://www.php.net/manual/en/mysqli.real-escape-string.php. The first parameter must be of type `string`, not `int`.

In non-strict mode, PHP automatically performs type conversion, so no error is thrown. However, this results in an ineffective call since applying mysqli_real_escape_string to a number is meaningless.

**Comment by LaySoft** [comment]
Thank you, that makes sense!
