### ISSUE TITLE
Event Loop - Common interface

### ISSUE THREAD

**Issue by ParkFramework** [swoole/swoole-src#626]
I think you need to take part in this decision.
https://github.com/async-interop/event-loop

**Why Bother?**

> 
> Some programming languages, such as Javascript, have an event loop that is native to the execution environment. This allows package vendors to easily create asynchronous software that uses this native event loop. Although PHP is historically a synchronous programming environment, it is still possible to use asynchronous programming techniques. Using these techniques, package vendors have created PHP event loop implementations that have seen success.
> 
> However, as these event loop implementations are from package vendors, it is not yet possible to create event driven software components that are independent of the underlying event loop implementation. By creating a common interface for an event loop, interoperability of this nature will be possible.
>

**Comment by matyhtf** [comment]
You can use PHP code that implements the interface.

**Comment by need-sleep** [comment]
I don't think it's possible, and I think it's the wrong direction at any rate. Swoole is able to out perform Node.js and other platforms that are typically faster than PHP because they try to maintain a clean native API which relies as little on PHP's/Zends's standard APIs such as streams. In fact most (all?) Swoole features are available without PHP, using libswoole. If I'm not mistaken none of Swoole's networking apis (Event loop, async sockets, coroutine sockets, redis, etc) are php stream compatible which seems to be a major point in their definition of event loop interoperability.
